package app.hfd.core.srs

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.double
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.long
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Replays review sequences generated by the reference implementation, py-fsrs 6.3.2 with its
 * defaults and fuzz off (tools/fsrs_reference.py), and expects the same states, stabilities,
 * difficulties and due dates.
 */
class FsrsTest {
    private val reference: JsonObject = Json.parseToJsonElement(
        javaClass.getResource("/fsrs_reference.json")!!.readText(),
    ).jsonObject
    private val fsrs = Fsrs(fuzz = false)

    private fun rating(s: String) = Rating.entries.first { it.name.lowercase() == s }

    @Test
    fun matchesTheReferenceImplementation() {
        for (name in listOf("A", "B", "C", "D")) {
            var card = SrsCard()
            (reference[name] as JsonArray).forEachIndexed { i, row ->
                val r = row.jsonObject
                val at = r["at"]!!.jsonPrimitive.long
                card = fsrs.review(card, rating(r["rating"]!!.jsonPrimitive.content), at)
                val where = "scenario $name, review ${i + 1}"
                assertEquals(where, r["state"]!!.jsonPrimitive.content, card.state.name.lowercase())
                assertEquals(where, (r["step"] as? JsonPrimitive)?.intOrNull, card.step)
                assertEquals(where, r["stability"]!!.jsonPrimitive.double, card.stability!!, 1e-9)
                assertEquals(where, r["difficulty"]!!.jsonPrimitive.double, card.difficulty!!, 1e-9)
                assertEquals(where, r["due"]!!.jsonPrimitive.long, card.due)
                assertEquals(where, at, card.lastReview)
                assertEquals(where, i + 1, card.reps)
            }
        }
    }

    @Test
    fun retrievabilityMatches() {
        val ref = reference["retrievability"]!!.jsonObject
        val card = SrsCard(
            state = CardState.REVIEW,
            stability = ref["stability"]!!.jsonPrimitive.double,
            difficulty = ref["difficulty"]!!.jsonPrimitive.double,
            lastReview = ref["lastReview"]!!.jsonPrimitive.long,
            due = ref["due"]!!.jsonPrimitive.long,
        )
        for (sample in ref["samples"]!!.jsonArray) {
            val s = sample.jsonObject
            assertEquals(s["r"]!!.jsonPrimitive.double, fsrs.retrievability(card, s["at"]!!.jsonPrimitive.long), 1e-12)
        }
        // At the due date, recall is about the desired retention.
        assertEquals(0.9, fsrs.strength(card, card.due), 0.02)
        assertEquals(0.0, fsrs.strength(SrsCard(), 0), 0.0)
    }

    @Test
    fun countsLapsesOnlyFromReview() {
        var card = SrsCard()
        card = fsrs.review(card, Rating.AGAIN, 0)
        assertEquals(0, card.lapses)
        card = fsrs.review(card, Rating.EASY, card.due)
        assertEquals(CardState.REVIEW, card.state)
        card = fsrs.review(card, Rating.AGAIN, card.due)
        assertEquals(1, card.lapses)
        assertEquals(CardState.RELEARNING, card.state)
        assertEquals(Rating.AGAIN, card.lastRating)
    }

    @Test
    fun fuzzStaysInRangeAndIsReproducible() {
        val fuzzy = Fsrs(fuzz = true)
        var card = SrsCard()
        var now = 0L
        repeat(8) {
            val plain = fsrs.review(card, Rating.GOOD, now)
            val a = fuzzy.review(card, Rating.GOOD, now, fuzzSeed = 42)
            val b = fuzzy.review(card, Rating.GOOD, now, fuzzSeed = 42)
            assertEquals(a, b)
            val plainDays = (plain.due - now) / Fsrs.DAY_MS
            val fuzzDays = (a.due - now) / Fsrs.DAY_MS
            if (plainDays >= 3) {
                val spread = 1 + 0.15 * (minOf(plainDays.toDouble(), 7.0) - 2.5) + 0.1 * maxOf(minOf(plainDays.toDouble(), 20.0) - 7, 0.0) + 0.05 * maxOf(plainDays - 20.0, 0.0)
                assertTrue("$plainDays → $fuzzDays", kotlin.math.abs(fuzzDays - plainDays) <= spread + 1)
            } else {
                assertEquals(plain.due, a.due)
            }
            card = plain
            now = plain.due
        }
    }
}
